### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by Thijxx** [syscoin/Masternode-Install-Script#12]
How does one update 4.2 to 4.2.1? Please add this to the README

**Comment by bigpoppa-sys** [comment]
Please follow guide below. I will be adjusting script shortly to auto upgrade with one click.

[Upgrade VPS Script Installs](https://support.syscoin.org/t/upgrading-your-4-2-masternodes-with-vps-script-install/482)

**Comment by Thijxx** [comment]
If I follow the guide and type in 4.2.1 it says STOPPING and then continues.. 
I think the branch is v4.2.1 so the `v` is missing in the guide but I tried it and it also does not work

**Comment by Thijxx** [comment]
Maybe it succeeded one of my tries and now it freaks out since it is already on 4.2.1
Tried 4.2.2 but that does not work..

**Comment by Thijxx** [comment]
Ok it worked now, also 4.2.2, rebooted the machines, no idea what the problem was.

So the guide works.

**Comment by sidhujag** [comment]
thanks, closing
